-- MySQL Script generated by MySQL Workbench
-- Sun Dec  2 18:58:00 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema web-con
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `rights`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rights` ;

CREATE TABLE IF NOT EXISTS `rights` (
  `id_rights` INT NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `weight` INT(2) NOT NULL,
  PRIMARY KEY (`id_rights`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users` ;

CREATE TABLE IF NOT EXISTS `users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `login` VARCHAR(30) NOT NULL,
  `pass` VARCHAR(40) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `rights_id_rights` INT NOT NULL,
  PRIMARY KEY (`id_user`),
  INDEX `fk_users_rights_idx` (`rights_id_rights` ASC) VISIBLE,
  CONSTRAINT `fk_users_rights`
    FOREIGN KEY (`rights_id_rights`)
    REFERENCES `rights` (`id_rights`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `posts` ;

CREATE TABLE IF NOT EXISTS `posts` (
  `id_posts` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(60) NOT NULL,
  `text` LONGTEXT NOT NULL,
  `datetime` DATETIME NOT NULL,
  `published` TINYINT NOT NULL,
  `users_id_user` INT NOT NULL,
  PRIMARY KEY (`id_posts`),
  INDEX `fk_posts_users1_idx` (`users_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_posts_users1`
    FOREIGN KEY (`users_id_user`)
    REFERENCES `users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rating`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rating` ;

CREATE TABLE IF NOT EXISTS `rating` (
  `language` INT(1) NOT NULL,
  `accuracy` INT(1) NOT NULL,
  `topic` INT(1) NOT NULL,
  `posts_id_posts` INT NOT NULL,
  `users_id_user` INT NOT NULL,
  PRIMARY KEY (`posts_id_posts`, `users_id_user`),
  INDEX `fk_rating_users1_idx` (`users_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_rating_posts1`
    FOREIGN KEY (`posts_id_posts`)
    REFERENCES `posts` (`id_posts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rating_users1`
    FOREIGN KEY (`users_id_user`)
    REFERENCES `users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contacts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `contacts` ;

CREATE TABLE IF NOT EXISTS `contacts` (
  `idcontacts` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(15) NOT NULL,
  `last_name` VARCHAR(25) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `phone_num` VARCHAR(15) NULL,
  PRIMARY KEY (`idcontacts`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `rights`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `rights` (`id_rights`, `name`, `weight`) VALUES (1, 'Author', 2);
INSERT INTO `rights` (`id_rights`, `name`, `weight`) VALUES (2, 'Reviewer', 5);
INSERT INTO `rights` (`id_rights`, `name`, `weight`) VALUES (3, 'Admin', 10);

COMMIT;

